#!/bin/bash

function vps_list {
	IS_LOCKED="$1"

	if [[ "$IS_LOCKED" ]]; then
		INDENT_COLOR=${GREEN}
	else
		INDENT_COLOR=${RED}
	fi

	CONTENT=$(tree "$DIR" -I 'LICENSE|README.md|.bin|.git*|.vps_*' --noreport | tail +2)
	while IFS= read -r LINE; do
		INDENT=$(echo "$LINE" | sed -E 's/^(.*)\s[a-zA-Z0-9\-\_\.].*$/\1/')
		ITEM=$(echo "$LINE" | sed -E 's/^[^a-zA-Z0-9\-\_\.]*(.*)$/\1/')

		if [[ "$ITEM" == *".gpg" ]]; then
			FILE=$(echo "$ITEM" | sed -E 's/^(.*).gpg/\1/')
			echo "${INDENT_COLOR}$INDENT ${YELLOW}$FILE"
		else
			echo "${INDENT_COLOR}$INDENT ${BLUE}$ITEM"
		fi
	done <<< "$CONTENT"
}
