#!/bin/bash

function vps_remove {
	DIR="$1"
	SOURCE="$2"

	echo "${RED}┬"

	if [[ -e "$DIR/$SOURCE.gpg" ]]; then

		echo "│   Deleting password file, this action is NOT reversible!"
		read -p "${RED}│   ${GREY}Would you like to ${YELLOW}remove the password file${GREY}? [y/N] " CONFIRM

		if [[ "$CONFIRM" == "Y" || "$CONFIRM" == "y" ]]; then
			echo "removing $DIR/$SOURCE.gpg"
			echo "│"
			echo "${RED}└── ${GREY}Password file deleted: ${GREEN}$SOURCE"
		fi

	elif [[ -d "$DIR/$SOURCE" ]]; then

		echo "│   WARNING!"
		echo "│   Deleting directory, this action is NOT reversible!"
		read -p "${RED}│   ${GREY}Would you like to ${YELLOW}remove the directory and all the password files within it${GREY}? [y/N] " CONFIRM

		if [[ "$CONFIRM" == "Y" || "$CONFIRM" == "y" ]]; then
			echo "removing $DIR/$SOURCE"
			echo "│"
			echo "${RED}└── ${GREY}Password directory deleted: ${GREEN}$SOURCE"
		fi

	else

		echo "│"
		echo "${RED}└── ${GREY}File or directory not found: ${GREEN}$SOURCE"

	fi
}
