#!/bin/bash

: '
TODO:
	- Set up install script for easy "get started"
	- Implement flags handler
	- Implement GnuPG ID check, unencrypted files check and throw warnings
	- Add file/dir not found function

	- Implement config file for UI, functionality and git
	- Implement config function
	- Implement autocomplete on TAB
	- Implement help function

	- Refactoring:
		- Add vps_print function
'

: '
╭────────────────────────────╮
│ ┏┓  .vilath   ┓  ┏┓        │
│ ┃┃┏┓┏┏┓┏┏┏┓┏┓┏┫  ┗┓╋┏┓┏┓┏┓ │
│ ┣┛┗┻┛┛┗┻┛┗┛┛ ┗┻  ┗┛┗┗┛┛ ┗  │
├────────────────────────────╯
│
├── Open-Source Password Manager by kilavila
├── https://github.com/kilavila/.vilath
│
└── GnuPG encrypted and locked with chattr, inspired by pass(passwordstore.org) but with improved functionality and UI.
		Automatically push changes to git, store passwords in hidden files and folders, view and copy passwords without unlocking with chattr etc.
		Generate strong passwords of any length, add additional information in password files and use commands you are familiar with!
		Commands like; cat, ls, cp, mv, rm etc..
		VPS also supports chaining commands, f.ex:
		vps gen web/twitch.tv edit web/twitch.tv view web/twitch.tv
		will generate a new password file, open it in the default editor and print it.
'

# alias vps='~/.vilath/.bin/vilath'
# _vps_autocomplete() {
# 	local cur prev words cword
#   _get_comp_words_by_ref -n = cur prev words cword
#
# 	if [[ ${prev} == "edit" ]] ||
# 		[[ ${prev} == "qr" ]] ||
# 		[[ ${prev} == "view" ]] || [[ ${prev} == "cat" ]] ||
# 		[[ ${prev} == "copy" ]] || [[ ${prev} == "cp" ]] ||
# 		[[ ${prev} == "move" ]] || [[ ${prev} == "mv" ]] ||
# 		[[ ${prev} == "remove" ]] || [[ ${prev} == "rm" ]];
# 	then
# 		local args=( $(find ~/.vilath -name '*.gpg' | sed -E 's/^.*\.vilath\/(.*)\.gpg$/\1/g') )
# 	else
# 		local args=( --help copy edit generate git initialize list lock move qr remove search unlock view )
# 	fi
#
#   COMPREPLY=( $(compgen -W "${args[*]}" -- $cur) )
# }
# complete -F _vps_autocomplete vps

USER=$(whoami)
DIR="/home/$USER/.vilath"

for VPS_FILE in $DIR/.bin/*.sh; do
	source "$VPS_FILE"
done

vps_cmd_handler "$@"
