#!/bin/bash

: '
╭────────────────────────────╮
│ ┏┓  .vilath   ┓  ┏┓        │
│ ┃┃┏┓┏┏┓┏┏┏┓┏┓┏┫  ┗┓╋┏┓┏┓┏┓ │
│ ┣┛┗┻┛┛┗┻┛┗┛┛ ┗┻  ┗┛┗┗┛┛ ┗  │
├────────────────────────────╯
├── Open-Source Password Manager by kilavila
├── https://github.com/kilavila/.vilath
│
└── GnuPG encrypted and locked with chattr, inspired by pass(passwordstore.org) but with improved functionality and UI.
		Automatically push changes to git, store passwords in hidden files and folders, view and copy passwords without unlocking with chattr etc.
		Generate strong passwords of any length, add additional information in password files and use commands you are familiar with!
		Commands like; cat, ls, cp, mv, rm etc..
		VPS also supports chaining commands, f.ex:
		vps gen web/twitch.tv edit web/twitch.tv view web/twitch.tv
		will generate a new password file, open it in the default editor and print it.
'

USER=$(whoami)
DIR="/home/$USER/.vilath"

source "$DIR/.bin/colors"
source "$DIR/.bin/copy"
source "$DIR/.bin/decrypt"
source "$DIR/.bin/edit"
source "$DIR/.bin/encrypt"
source "$DIR/.bin/initialize"
source "$DIR/.bin/generate"
source "$DIR/.bin/list"
source "$DIR/.bin/move"
source "$DIR/.bin/remove"
source "$DIR/.bin/view"

CHATTR=$(lsattr -dR "$DIR" | awk '{print $1}')
if [[ "$CHATTR" == *"i"* ]]; then
	IS_LOCKED=true;
fi

: '
╭─────────────────╮
│ Actions handler │
├─────────────────╯
'
if [[ "$#" > 0 ]]; then
	for PARAM in "$@"; do
		if [[ "$PARAM" == "unlock" ]]; then UNLOCK=true;
		elif [[ "$PARAM" == "lock" ]]; then LOCK=true;
		elif [[ "$PARAM" == "initialize" || "$PARAM" == "init" ]]; then INITIALIZE=true;
		elif [[ "$PARAM" == "generate" || "$PARAM" == "gen" ]]; then GENERATE=true;
		elif [[ "$PARAM" == "edit" ]]; then EDIT=true;
		elif [[ "$PARAM" == "view" || "$PARAM" == "cat" ]]; then VIEW=true;
		elif [[ "$PARAM" == "list" || "$PARAM" == "ls" ]]; then LIST=true;
		elif [[ "$PARAM" == "copy" || "$PARAM" == "cp" ]]; then COPY=true;
		elif [[ "$PARAM" == "move" || "$PARAM" == "mv" ]]; then MOVE=true;
		elif [[ "$PARAM" == "remove" || "$PARAM" == "rm" ]]; then REMOVE=true;
		elif [[ "$PARAM" == "git" ]]; then GIT=true;
		fi
	done
else LIST=true;
fi

function vps_locked_error {
	echo "${GREEN}│   ${RED}Unauthorized!"
	echo "${GREEN}└── ${GREY}This action is not allowed while VPS is locked.${NC}"
}

function vps_get_file {
	PARAMS="$@"
	VCMD="$1"

	if [[ "$VCMD" == "vps_gen_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(generate|gen)\s+(.*)$/\3/')
	elif [[ "$VCMD" == "vps_edit_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(edit)\s+(.*)$/\3/')
	elif [[ "$VCMD" == "vps_view_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(view|cat)\s+(.*)$/\3/')
	elif [[ "$VCMD" == "vps_copy_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(copy|cp)\s+(.*)$/\3/')
		TARGET_FILE_REQUIRED=true
	elif [[ "$VCMD" == "vps_move_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(move|mv)\s+(.*)$/\3/')
		TARGET_FILE_REQUIRED=true
	elif [[ "$VCMD" == "vps_remove_cmd" ]]; then
		CMD=$(echo "$PARAMS" | sed -E 's/^(.*)?(remove|rm)\s+(.*)$/\3/')
	fi

	if [[ "$TARGET_FILE_REQUIRED" ]]; then
		SOURCE=$(echo "$CMD" | awk '{print $1}')
		TARGET=$(echo "$CMD" | awk '{print $2}')
		echo "$SOURCE $TARGET"
	else
		SOURCE=$(echo "$CMD" | awk '{print $1}')
		echo "$SOURCE"
	fi
}

function vps_cmd_handler {
	PARAMS="$@"

	: '
	╭──────╮
	│ Lock │
	├──────╯
	'
	if [[ "$UNLOCK" ]]; then
		sudo chattr -i -R "$DIR"
		echo "${RED}VPS Unlocked${NC}"
		return 0
	fi
	if [[ "$LOCK" ]]; then
		sudo chattr +i -R "$DIR"
		echo "${GREEN}VPS Locked${NC}"
		return 0
	fi

	: '
	╭────────╮
	│ Header │
	├────────╯
	'
	if [[ "$IS_LOCKED" ]]; then
		echo " ${GREEN}╭────────────────────────────╮"
		echo " │ ${GREY}┏┓  ${DARK_GREY}.vilath   ${GREY}┓  ┏┓        ${GREEN}│"
		echo " │ ${GREY}┃┃┏┓┏┏┓┏┏┏┓┏┓┏┫  ┗┓╋┏┓┏┓┏┓ ${GREEN}│"
		echo " │ ${GREY}┣┛┗┻┛┛┗┻┛┗┛┛ ┗┻  ┗┛┗┗┛┛ ┗  ${GREEN}│"
		echo "┌┴────────────────────────────┴┐"
		echo "│${NC}"
	else
		echo " ${RED}╭────────────────────────────╮"
		echo " │ ${GREY}┏┓  ${DARK_GREY}.vilath   ${GREY}┓  ┏┓        ${RED}│"
		echo "   ${GREY}┃┃┏┓┏┏┓┏┏┏┓┏┓┏┫  ┗┓╋┏┓┏┓┏┓ ${RED}│"
		echo "   ${GREY}┣┛┗┻┛┛┗┻┛┗┛┛ ┗┻  ┗┛┗┗┛┛ ┗  ${RED}│"
		echo "┌─────────────────────────────┴┐"
		echo "┴${NC}"
	fi

	: '
	╭────────────╮
	│ Initialize │
	├────────────╯
	'
	if [[ "$INITIALIZE" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		GPG_ID=$(echo "$PARAMS" | sed -E 's/^.*(initialize|init)\s+([a-zA-Z0-9\-\_\.\@]+).*$/\2/')
		vps_initialize "$DIR" "$GPG_ID"
	fi

	: '
	╭──────────╮
	│ Generate │
	├──────────╯
	'
	if [[ "$GENERATE" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		SOURCE=$(vps_get_file "vps_gen_cmd" "$PARAMS")
		vps_generate "$DIR" "$SOURCE"
	fi

	: '
	╭──────╮
	│ Edit │
	├──────╯
	'
	if [[ "$EDIT" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		SOURCE=$(vps_get_file "vps_edit_cmd" "$PARAMS")
		vps_edit "$DIR" "$SOURCE"
	fi

	: '
	╭──────╮
	│ View │
	├──────╯
	'
	if [[ "$VIEW" ]]; then
		SOURCE=$(vps_get_file "vps_view_cmd" "$PARAMS")
		vps_view "$IS_LOCKED" "$DIR" "$SOURCE"
	fi

	: '
	╭──────╮
	│ Copy │
	├──────╯
	'
	if [[ "$COPY" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		SOURCE_TARGET=$(vps_get_file "vps_copy_cmd" "$PARAMS")
		SOURCE_FILE=$(echo "$SOURCE_TARGET" | awk '{print $1}')
		TARGET_FILE=$(echo "$SOURCE_TARGET" | awk '{print $2}')
		vps_copy "$DIR" "$SOURCE_FILE" "$TARGET_FILE"
	fi

	: '
	╭──────╮
	│ Move │
	├──────╯
	'
	if [[ "$MOVE" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		SOURCE_TARGET=$(vps_get_file "vps_move_cmd" "$PARAMS")
		SOURCE_FILE=$(echo "$SOURCE_TARGET" | awk '{print $1}')
		TARGET_FILE=$(echo "$SOURCE_TARGET" | awk '{print $2}')
		vps_move "$DIR" "$SOURCE_FILE" "$TARGET_FILE"
	fi

	: '
	╭────────╮
	│ Remove │
	├────────╯
	'
	if [[ "$REMOVE" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		SOURCE=$(vps_get_file "vps_remove_cmd" "$PARAMS")
		vps_remove "$DIR" "$SOURCE"
	fi

	: '
	╭──────╮
	│ List │
	├──────╯
	'
	if [[ "$LIST" ]]; then
		if ! [[ "$IS_LOCKED" ]]; then
			echo "${RED}┬${NC}"
		fi
		vps_list "$IS_LOCKED"
	fi

	: '
	╭─────╮
	│ Git │
	├─────╯
	'
	if [[ "$GIT" ]]; then
		if [[ "$IS_LOCKED" ]]; then vps_locked_error; return 0; fi

		echo "${BLUE}Work in progress..."
		echo "Git options"
	fi

	echo "${NC}"
}

vps_cmd_handler "$@"
